version: '2'
services:
  mongo:
    image: mongo
    container_name: database

  server:
    image: klskvmr/eacademy
    environment:
      - spring.data.mongodb.host=database
    ports:
      - 5184:8089